### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'translate'

### ISSUE THREAD

**Issue by prostomarkeloff** [timoniq/vbml#2]
Traceback:
```py
vkbot_1     | Traceback (most recent call last):
vkbot_1     |   File "bot/main.py", line 38, in run
vkbot_1     |     handlers_init()
vkbot_1     |   File "bot/main.py", line 30, in handlers_init
vkbot_1     |     dp.setup_blueprint(echo_bp)
vkbot_1     |   File "/usr/local/lib/python3.7/site-packages/vk/bot_framework/dispatcher/dispatcher.py", line 287, in setup_blueprint
vkbot_1     |     named_rules = self._rule_factory.get_rules(handler.named_rules)
vkbot_1     |   File "/usr/local/lib/python3.7/site-packages/vk/bot_framework/dispatcher/rule.py", line 76, in get_rules
vkbot_1     |     rule: BaseRule = self.config[key](value)
vkbot_1     |   File "/usr/local/lib/python3.7/site-packages/vk/bot_framework/rules/rules.py", line 388, in __init__
vkbot_1     |     pattern
vkbot_1     |   File "/usr/local/lib/python3.7/site-packages/vbml/patcher/patcher.py", line 28, in pattern
vkbot_1     |     return Pattern(text, **context)
vkbot_1     |   File "/usr/local/lib/python3.7/site-packages/vbml/patcher/pattern/pattern.py", line 95, in __init__
vkbot_1     |     pre=pre.translate(self.escape),
vkbot_1     | AttributeError: 'NoneType' object has no attribute 'translate'
```
Help me :(

**Comment by timoniq** [comment]
Oops, I crapped. I gonna fix it right now.
